### ISSUE TITLE
scons command does not work on Windows

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/scons-feedstock#2]
On Windows the `scons` command fails:

```
C:\User\builder>conda create -n foo python=3.6 scons -c conda-forge
...
C:\User\builder>activate foo

(foo) C:\User\builder>scons -h
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
...
```

Running the scons.py Python script directly works fine:

```
(foo) C:\User\builder>python C:\Users\builder\Anaconda3\envs\foo\Scripts\scons.py -h
usage: scons [OPTION] [TARGET] ...
```

**Comment by jakirkham** [comment]
Does that issue occur with Python 2 as well? Other OSes? Also could you please include an environment file for the reproducer?

**Comment by stuertz** [comment]
I can simply reproduce this. 
Does only occur with Py3. Py2 does work on windows.
The problem seems to be extending PATH Environment Variable in https://github.com/SCons/scons/blob/master/src/script/scons.bat#L19
After commenting that line out, it seems to work.

Looks to me as if that PATH extension is at least not required within conda envs.

**Comment by nicoddemus** [comment]
Bummer, somehow I forgot to apply the patch and it passed somehow. Will try rebuilding 3.0.1.
